# This is a basic workflow to help you get started with Actions

name: Sync QA Wolf tests

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "fetch"
  fetch-qawolf-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Download on copy tests and helpers
        env:
          QAWOLF_TEAM_ID: ${{ secrets.QAWOLF_TEAM_ID }}
          QAWOLF_AUTH_TOKEN: ${{ secrets.QAWOLF_AUTH_TOKEN }}
        run: |
          cd ./github/workflow/ ; npm install
          node ./github/workflow/index.js

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add ./qawolf/*
          git commit -m "QA Wolf tests sync $(date +"%Y-%m-%d")"
          git push origin main
